import os
os.system("complementos.py")
os.system("prog_dermocosmeticos.py")
os.system("tendencias.py")
os.system("vitaminas.py")
os.system("cuidadobucal.py")
os.system("prog_marcas_cosmeticos_ve.py")
os.system("primeros.py")
os.system("Cuidado_facial.py")
os.system("estrategia.py")
os.system("Cosméticos_Avanzados.py")
os.system("Nutrición.py")
os.system("marcas_co.py")
os.system("Medicamentos_RX.py")
os.system("Medicinas_OTC.py")
os.system("prog_cuidado_del_cabello.py")
os.system("SF_VE.py")
os.system("SF_Co.py")

