import re
import time
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context(storage_state="auth.json")
    page = context.new_page()
    page.goto("https://drive.google.com/drive/folders/0AAjNTltlHaksUk9PVA")
    page.locator("div").filter(has_text=re.compile(r"^NUEVOS INGRESOS$")).first.dblclick()
    with page.expect_popup() as page1_info:
        page.get_by_label("Copia de NUEVOS INGRESOS-").dblclick()
    page1 = page1_info.value
    page1.goto("https://docs.google.com/spreadsheets/d/1IE_W4RftuI_0tXX411CR0eDWDPlIM3JjsOTWaWv7SZQ/edit?gid=1585319799#gid=1585319799")
    page1.get_by_label("Ingresa el nombre del archivo").fill("C")
    page1.get_by_label("Ingresa el nombre del archivo").click()
    page1.locator(".javascriptMaterialdesignGm3WizTextFieldOutlined-text-field").click()
    page1.get_by_label("Ingresa el nombre del archivo").fill("Cuidado del Cabello")
    page1.get_by_role("button", name="Aceptar").click()
    page1.get_by_label("Ingresa el nombre de la hoja").fill("Hoja 1")
    page1.get_by_role("button", name="Aceptar").click()
    page1.get_by_role("button", name="Sí").click()
    page1.get_by_role("button", name="Aceptar").click()
    time.sleep(1)
    page1.get_by_role("button", name="Aceptar").click()
    time.sleep(1)
    page1.get_by_role("menuitem", name="Extensiones").click()
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("ArrowRight")
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    
    time.sleep(1)
    page1.keyboard.press("Enter")
    time.sleep(1)
   # page1.get_by_role("span", name="calcularEstadoYActividadNUEVOSINGRESOS").click()
    time.sleep(1)
    #page1.get_by_role("menuitem", name="agregarAreaTiendaNivelCargo2", exact=True).click()
    page1.get_by_role("menuitem", name="Extensiones").click()
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("ArrowRight")
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("Enter")
    time.sleep(2)
    
    page1.get_by_role("menuitem", name="Extensiones").click()
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("ArrowRight")
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("ArrowDown")
    time.sleep(1)
    page1.keyboard.press("Enter")
    time.sleep(1)
    #page1.get_by_text("eliminarFilas").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)