name: Weekly File Download & Upload

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 3'

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src

    strategy:
      fail-fast: false
      matrix:
        task:
          - Manejo
          - Pilares
          - control

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        if: matrix.task == 'Pilares'
        run: |
          # This installs Chromium, Firefox, WebKit for Playwright
          python -m playwright install

      - name: "Debug: show workspace layout"
        run: |
          echo "PWD: $(pwd)"
          ls -R .

      - name: Run downloader ${{ matrix.task }}
        run: python download.py ${{ matrix.task }}
        continue-on-error: true
        env:
          F_EMAIL:      ${{ secrets.F_EMAIL }}
          F_PASSWORD:   ${{ secrets.F_PASSWORD }}
          DOWNLOAD_DIR: ${{ github.workspace }}/downloads/${{ matrix.task }}

      - name: Upload debug artifacts for ${{ matrix.task }}
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ matrix.task }}
          path: |
            downloads/${{ matrix.task }}/error.html
            downloads/${{ matrix.task }}/error.png

      - name: Upload ${{ matrix.task }} to Google Drive
        if: success()
        run: |
          python src/descarga_archivos/upload_to_drive.py \
            "${{ github.workspace }}/downloads/${{ matrix.task }}/${{ matrix.task }}.xlsx"
        env:
          GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          GDRIVE_FOLDER_ID:      ${{ secrets.GDRIVE_FOLDER_ID }}
